CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS prompts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sequence_index INTEGER NOT NULL UNIQUE,
  text TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('free_form', 'task_oriented', 'short_command', 'hard_transcription', 'read_speech', 'turn_taking')),
  active BOOLEAN NOT NULL DEFAULT true,
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  target_contexts JSONB NOT NULL DEFAULT '[]'::jsonb,
  pair_group_id TEXT,
  canonical_transcript TEXT,
  priority INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS commutes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status TEXT NOT NULL CHECK (status IN ('active', 'ended')) DEFAULT 'active',
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ,
  current_prompt_id UUID REFERENCES prompts(id),
  current_prompt_index INTEGER NOT NULL DEFAULT 0,
  start_lat DOUBLE PRECISION NOT NULL,
  start_lon DOUBLE PRECISION NOT NULL,
  start_accuracy DOUBLE PRECISION NOT NULL,
  device_motion_json JSONB,
  device_orientation_json JSONB,
  screen_info_json JSONB,
  audio_route_json JSONB,
  client_ua TEXT,
  client_platform TEXT,
  client_viewport TEXT,
  client_locale TEXT,
  client_timezone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS recordings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  commute_id UUID NOT NULL REFERENCES commutes(id) ON DELETE CASCADE,
  prompt_id UUID NOT NULL REFERENCES prompts(id),
  prompt_text_snapshot TEXT NOT NULL,
  object_key TEXT NOT NULL UNIQUE,
  object_url TEXT NOT NULL,
  capture_status TEXT NOT NULL DEFAULT 'uploaded' CHECK (capture_status IN ('uploaded')),
  duration_ms INTEGER NOT NULL,
  file_size_bytes BIGINT NOT NULL,
  content_type TEXT NOT NULL,
  capture_started_at TIMESTAMPTZ NOT NULL,
  capture_ended_at TIMESTAMPTZ NOT NULL,
  upload_completed_at TIMESTAMPTZ NOT NULL,
  location_lat DOUBLE PRECISION,
  location_lon DOUBLE PRECISION,
  location_speed DOUBLE PRECISION,
  location_heading DOUBLE PRECISION,
  location_altitude DOUBLE PRECISION,
  location_accuracy DOUBLE PRECISION,
  motion_accel_x DOUBLE PRECISION,
  motion_accel_y DOUBLE PRECISION,
  motion_accel_z DOUBLE PRECISION,
  motion_accel_gravity_x DOUBLE PRECISION,
  motion_accel_gravity_y DOUBLE PRECISION,
  motion_accel_gravity_z DOUBLE PRECISION,
  motion_rot_alpha DOUBLE PRECISION,
  motion_rot_beta DOUBLE PRECISION,
  motion_rot_gamma DOUBLE PRECISION,
  motion_interval_ms DOUBLE PRECISION,
  orientation_alpha DOUBLE PRECISION,
  orientation_beta DOUBLE PRECISION,
  orientation_gamma DOUBLE PRECISION,
  orientation_absolute BOOLEAN,
  compass_heading DOUBLE PRECISION,
  compass_accuracy DOUBLE PRECISION,
  audio_track_settings_json JSONB,
  audio_devices_json JSONB,
  audio_context_sample_rate INTEGER,
  audio_context_base_latency DOUBLE PRECISION,
  screen_orientation_type TEXT,
  screen_orientation_angle INTEGER,
  client_ua TEXT,
  client_platform TEXT,
  client_locale TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (commute_id, prompt_id)
);
